editables:
    graphics/aa960a2385@adnn/develop:
        path: ../../../graphics/conan
    math/541fce5f6a@adnn/develop:
        path: ../../../math/conan
    focg/local:
        path: ../../../focg/conan
layout: layout
workspace_generator: cmake
root: focg/local
